apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: devops-lab-app
  namespace: devops-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopslab-app
  template:
    metadata:
      labels:
        app: devops-lab-app
    spec:
      containers:
        - name: app
          image: ACR_LOGIN_SERVER/devops-lab-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
